# Generated by Django 4.1 on 2023-04-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBlog',
            fields=[
                ('search_blog_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('search_blog_content', models.TextField(blank=True, max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerBlog',
            fields=[
                ('answer_blog_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('answer_blog_title', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_blog_author', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_blog_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_blog_article', models.TextField(blank=True, max_length=50000)),
                ('search_blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.searchblog')),
            ],
        ),
    ]
